services:
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    restart: unless-stopped
    hostname: unbound
    volumes:
      - ./config/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    networks:
      privacy_net:
        ipv4_address: 10.10.10.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    depends_on:
      - unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      - TZ=Europe/Madrid
      - WEBPASSWORD=admin
      - PIHOLE_DNS_=10.10.10.2#53
      - DNSSEC=true
      - DNSMASQ_LISTENING=all
    volumes:
      - ./config/pihole/etc-pihole:/etc/pihole
      - ./config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      privacy_net:
        ipv4_address: 10.10.10.3

networks:
  privacy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
